/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Application.MainController;
import Data.ClassRoom;
import Data.PracticalClassroom;
import Data.Professor;
import Data.Student;
import Data.TheoreticalClassroom;
import Data.User;
import java.util.LinkedList;
import shedulesadministrator.ShedulesAdministrator;
import static shedulesadministrator.ShedulesAdministrator.ins;

/**
 *
 * @author Ricardo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUserName = new javax.swing.JTextField();
        jPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBounds(new java.awt.Rectangle(500, 500, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 300, 40));
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 300, 40));

        jLabel1.setFont(new java.awt.Font("Batang", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Schedule Administrator");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 410, 50));

        btLogin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btLogin.setForeground(new java.awt.Color(0, 0, 102));
        btLogin.setText("Sign in");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 130, 50));

        jLabel2.setFont(new java.awt.Font("Batang", 3, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 90, 20));

        jLabel4.setFont(new java.awt.Font("Batang", 3, 14)); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 90, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 340, 170));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 490, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed

        if (ins.login(jUserName.getText(), jPassword.getText())) {
            CoordinatorHome home = new CoordinatorHome();
            home.setVisible(true);
            int count = ShedulesAdministrator.ins.countUsers();
            LinkedList<User> tempUser = ShedulesAdministrator.ins.getUsers();
            boolean firstTimeP = true;
            boolean firstTimeS = true;
            // ShedulesAdministrator.ins.user

            //add the user the the Combobox User
            while (count >= 0) {
                if (tempUser.get(count) instanceof Professor && firstTimeP) {
                    home.jComboBoxTeacher.addItem(tempUser.get(count).getId());
                    home.jTextFieldTeacherID.setText(tempUser.get(count).getId());
                    home.jTextFieldTeacherName.setText(tempUser.get(count).getName());
                    home.jTextFieldTeacherDepartment.setText(((Professor) tempUser.get(count)).getDepartment().getName());
                    home.jTextFieldStudentPassword.setText(tempUser.get(count).getPassword());
                    home.jCheckBoxCoordinator.setSelected(((Professor) tempUser.get(count)).isCoordinator());
                    firstTimeP = false;
                    count--;
                }
                if (tempUser.get(count) instanceof Professor && !firstTimeP) {

                    home.jComboBoxTeacher.addItem(tempUser.get(count).getId());
                    count--;
                } else if (firstTimeS) {
                    home.jComboBoxStudent.addItem(tempUser.get(count).getId());
                    home.jTextFieldStudentName.setText(tempUser.get(count).getName());
                    home.jTextFieldStudentID.setText(tempUser.get(count).getId());
                    home.jTextFieldStudentCard.setText(((Student) tempUser.get(count)).getStudentCard());
                    home.jTextFieldStudentPassword.setText(tempUser.get(count).getPassword());
                    firstTimeS = false;
                    count--;
                } else {
                    home.jComboBoxStudent.addItem(tempUser.get(count).getId());
                    count--;
                }

            }

            int countClassRoom = ins.countClassRoom();
            LinkedList<ClassRoom> tempClassRooms = ins.getClassRooms();
            boolean firsTimeClass=true;

            while (countClassRoom >= 0) {
                if(firsTimeClass){
                ins.currentClassRoom=tempClassRooms.get(countClassRoom);
                home.jComboBoxClassRoomName.addItem(tempClassRooms.get(countClassRoom).getName());
                home.jTextFieldClassRoomName.setText(tempClassRooms.get(countClassRoom).getName());
                home.jTextFieldClassRoomNumber.setText(String.valueOf(tempClassRooms.get(countClassRoom).getClassRoomNumber()));
                home.jTextFieldClassRoomCapacity.setText(String.valueOf(tempClassRooms.get(countClassRoom).getCapacity()));
                home.jTextFieldClassRoomLocation.setText(tempClassRooms.get(countClassRoom).getLocation());
                firsTimeClass=false;
                if (tempClassRooms.get(countClassRoom) instanceof TheoreticalClassroom) {
                    home.jCheckBoxAirConditioning.setSelected(((TheoreticalClassroom) tempClassRooms.get(countClassRoom)).getAirConditioning());
                    home.jCheckBoxMultimediaItems.setSelected(((TheoreticalClassroom) tempClassRooms.get(countClassRoom)).getMultimediaEquipment());
                    countClassRoom--;
                }
                if (tempClassRooms.get(countClassRoom) instanceof PracticalClassroom) {
                    home.jTextFieldEquipmentAvailable.setText(((PracticalClassroom) tempClassRooms.get(countClassRoom)).getEquipmentAvailable());
                    home.jTextFieldAmountEquipment.setText(String.valueOf(((PracticalClassroom) tempClassRooms.get(countClassRoom)).getAmountEquipment()));
                    countClassRoom--;
                }
                
                }
                else{
                 home.jComboBoxClassRoomName.addItem(tempClassRooms.get(countClassRoom).getName());
                }
            }




    }//GEN-LAST:event_btLoginActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jPassword;
    public javax.swing.JTextField jUserName;
    // End of variables declaration//GEN-END:variables
}
